# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GISAuditorReport
                                 A QGIS plugin
 It allows users to define and run a series of essential validation checks across vector layers and standalone attribute tables within a QGIS project. It helps users identify data quality issues by checking shared keys, spatial relationships, and duplicate values, with results available in clear, exportable reports.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-09-28
        copyright            : (C) 2025 by Lei Ding
        email                : lleidding@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load GISAuditorReport class from file GISAuditorReport.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .gis_auditor_report import GISAuditorReport
    return GISAuditorReport(iface)
