# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GISAuditorReportDialog
                                 A QGIS plugin
 It allows users to define and run a series of essential validation checks across vector layers and standalone attribute tables within a QGIS project. It helps users identify data quality issues by checking shared keys, spatial relationships, and duplicate values, with results available in clear, exportable reports.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-09-28
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Lei Ding
        email                : lleidding@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
from qgis.PyQt.QtWidgets import QDialogButtonBox
# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'gis_auditor_report_dialog_base.ui'))



class GISAuditorReportDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(GISAuditorReportDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        
        self.setupUi(self)
        ok_button = self.button_box.button(QDialogButtonBox.Ok)
        if ok_button:
            # change to run
            ok_button.setText("Run")

            ok_button.setObjectName("runButton")